apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.controller.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      {{- include "kmerge.Controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.controller.podAnnotations .Values.global.commonAnnotations }}
      annotations:
        {{- if .Values.global.commonAnnotations }}
        {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.controller.podAnnotations }}
        {{- include "tplvalues.render" ( dict "value" .Values.controller.podAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
        {{- end }}
      labels:
        {{- include "kmerge.Controller.selectorLabels" . | nindent 8 }}
        {{- if .Values.global.commonLabels }}
        {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.controller.podLabels }}
        {{- include "tplvalues.render" ( dict "value" .Values.controller.podLabels "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.controller.image.imagePullSecrets }}
      imagePullSecrets:
      {{- with .Values.controller.image.imagePullSecrets }}
      {{- toYaml . | trim | nindent 6 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ .Values.controller.name | trunc 63 | trimSuffix "-" }}
      priorityClassName: {{ default "system-node-critical" .Values.controller.priorityClassName }}
      restartPolicy: Always
      {{- with .Values.controller.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.controller.name | trunc 63 | trimSuffix "-" }}
        image: {{ include "kmerge.Controller.image" . | quote }}
        imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
        command:
        - {{ .Values.controller.binName }}
        args:
        - daemon
        {{- with .Values.controller.extraArgs }}
        {{- toYaml . | trim | nindent 8 }}
        {{- end }}
        {{- with .Values.controller.resources }}
        resources:
        {{- toYaml . | trim | nindent 10 }}
        {{- end }}
        lifecycle:
          preStop:
            exec:
              command:
                - {{ .Values.controller.binName }}
                - shutdown
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- with .Values.controller.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.controller.securityContext }}
        securityContext:
        {{- toYaml . | nindent 8 }}
        {{- end }}
