apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kmerge-controller-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kmerge-controller-admin
subjects:
- kind: ServiceAccount
  name: {{ .Values.controller.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}